title: Alexia Telios
description: Chemistry PhD student | protein design | 
theme: jekyll-theme-minimal

# Optional: show downloads link in minimal theme
show_downloads: false

# Optional: these help GitHub Pages builds
plugins:
  - jekyll-seo-tag
